{{ if eq .chezmoi.os "linux" -}}
{{- $hasAgeKey := stat (joinPath .chezmoi.homeDir ".config/chezmoi/key.txt") -}}
{{ if and (eq .chezmoi.hostname "victus") $hasAgeKey -}}
# add WIP repos

"projects/download-geofabrik":
    type: git-repo
    url: "git@github.com:julien-noblet/download-geofabrik.git"
    refreshPeriod: "24h"
"projects/cad-killer":
    type: git-repo
    url: "git@github.com:julien-noblet/cad-killer.git"
    refreshPeriod: "24h"
"projects/julien-noblet.github.io":
    type: git-repo
    url: "git@github.com:julien-noblet/julien-noblet.github.io.git"
    refreshPeriod: "2h"
"projects/ebcdic":
    type: git-repo
    url: "git@github.com:julien-noblet/ebcdic.git"
    refreshPeriod: "2h"
"projects/k8s/cwa":
    type: git-repo
    url: "git@github.com:julien-noblet/k8s-cwa.git"
    refreshPeriod: "24h"
"projects/k8s/manifolds":
    type: git-repo
    url: "git@github.com:julien-noblet/k8s-manifold.git"
    refreshPeriod: "24h"
"projects/k8s/blocky":
    type: git-repo
    url: "git@github.com:julien-noblet/terraform-blocky.git"
    refreshPeriod: "24h"
"projects/k8s/readeck":
    type: git-repo
    url: "git@github.com:julien-noblet/kubernetes-readeck.git"
    refreshPeriod: "24h"
"projects/k8s/miniflux":
    type: git-repo
    url: "git@github.com:julien-noblet/kubernetes-miniflux.git"
    refreshPeriod: "24h"
"projects/k8s/tools":
    type: git-repo
    url: "git@github.com:julien-noblet/kubernetes-tools.git"
    refreshPeriod: "24h"
"projects/3d-printer-calculator":
    type: git-repo
    url: "git@gitlab.com:julien-noblet/3dcost.git"
    refreshPeriod: "24h"
"projects/miniflux-auto-read":
    type: git-repo
    url: "git@github.com:julien-noblet/miniflux-auto-read.git"
    refreshPeriod: "24h"
#"projects/gitea":
#    type: git-repo
#    url: "ssh://git@gitea.local:2222/julien/k8s-gitea.git"
#    refreshPeriod: "24h"

## tools
# kubectl
# curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
# install in /usr/local/bin and make it executable
"bin/kubectl":
    type: file
    url: "https://dl.k8s.io/release/v1.35.0/bin/linux/amd64/kubectl"
    refreshPeriod: "24h"
    executable: true

{{ end }}

# NixOS
{{ if or (eq .chezmoi.os "nixos") (eq .chezmoi.hostname "victus") -}}
"flake"
    type: git-repo
    url: "git@github.com:julien-noblet/nix.git"
    refreshPeriod: "2h"

{{ end }}

# Install ender3pro
{{ if eq .chezmoi.hostname "ender3pro" }}
"kiauh":
    type: git-repo
    url: https://github.com/th33xitus/kiauh.git
    refreshPeriod: "24h"

{{ end }}
{{ end -}}
